### ISSUE TITLE
Problem z wtyczką viaplay

### ISSUE THREAD

**Issue by RagnarLodbrok1981** [Repozytorium-Kodi/Repozytorium-Kodi#1]
Dzień dobry.
Mam problem z wtyczką viaplay, chciałem zobaczyć w nocy mecz MLB pomiędzy Toronto Blue Jays - Baltimore Orioles.
Niestety ciągle pojawiał się komunikat "Nieudane odtwarzanie jednej lub więcej pozycji. Więcej informacji na ten 

temat znajdziesz w pliku dziennika diagnostycznego". Sprawdziłem na stronie www, tam mecz leciał.
Kilka informacji zapewne przydatnych:
kodi 20.02 nexus
smart tv android
wtyczka wersja ( 2.3.9 pobrana z Repozytorium-Kodi-1.0.4 - Nexus/zips - plugin.video.viaplay - plugin.video.viaplay-2.3.9.zip
oraz log:
https://paste.kodi.tv/obutopayik
Czy da się to naprawić? Byłbym wdzięczny.
Pozdrawiam.

**Comment by zuzia-dev** [comment]
Rozwiązane: https://github.com/mtr81/kodi_addons/issues/30
